

    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-4">
          <h2>ZF 1.12</h2>
          <p>Este es una plantilla para empezar un proyecto en Zend versi&oacute;n 1.12. Contiene el framework de Bootstrap 3.1</p>
        </div>
        
      </div>

      <hr>

      <footer>
        <p>© Kode-I 2014</p>
      </footer>
    </div> <!-- /container -->
